units_type: character
feature_source: kaldi
feature_type: mfcc
data:
    name: aishell
    vocab: labels_ch.txt
    left_context_width: 3
    right_context_width: 0
    frame_rate: 30
    features_dim: 80
    merge_num: 4
    flat_num: 3
    apply_cmvn: True
    max_input_length: 550
    max_target_length: 50
    batch_size: 10
    short_first: True
    shuffle: True
    train: wav_txt/aishell.train
    dev: wav_txt/aishell.dev
    test: wav_txt/aishell.test
    PAD_INDEX: 0
    SOS_INDEX: 1
    EOS_INDEX: 2
    UNK_INDEX: 3
    BLANK_INDEX: 4
model:
    type: transducer
    lm_pre_train: False
    lm_model_path: lm_model/decoder_LM_model
    ctc_pre_train: False
    ctc_model_path: ctc_model2/6_0.1567_enecoder_model
    enc:
        type: lstm
        hidden_size: 512
        project_size: 256
        output_size: 320
        n_layers: 4
        bidirectional: False
    dec:
        type: lstm
        hidden_size: 512
        project_size: 256
        output_size: 320
        n_layers: 1
    joint:
        input_size: 640
        inner_size: 1024
    vocab_size: 4337
    share_weight: False
    input_size: 320
    dropout: 0.2
training:
    load_model: False
    load_encoder: False
    load_decoder: False
    eval_or_not: True
    seed: 2019
    num_gpu: 1
    epochs: 100
    max_grad_norm: 200
    visualization: True
    show_interval: 10
    save_model: rnnt-model
optim:
    type: adam
    lr: 0.0005
    momentum: 0.9
    decay_ratio: 0.5
    weight_decay: 0
    begin_to_adjust_lr: 5